 
IE ="Ie"
IE_PATH="C:\Temp\src\IEDriverServer_x64\IEDriverServer"
CHROME = "Chrome"
FIREFOX = "firefox"
INDEX = "http://google.com/"
CASES="cases"
CONTENT="data"

URL="url"
CLICK="click"
TEXT="text"
PASSWORD="pwd"
DROPDOWN="dropdown"
TRUE="true"
ID="id"
NAME="name"